version: '3.4'
services:
  postgres:
    image: postgres:10.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: you_can_call_me_karaok_al
      POSTGRES_USER: you_can_call_me_karaok_al
      POSTGRES_PASSWORD: Karaoke4Life!
    ports:
        - "5432:5432"
    volumes:
        - "karaokAldata:/var/lib/postgresql/data"
volumes:
  karaokAldata:
